dataset_name: 'inspection'
camera_params:
  image_height: 480
  image_width: 848
  fx: 617.832096
  fy: 621.743364
  cx: 427.447679
  cy: 233.692923
  png_depth_scale: 1000  # 1000 for Replica provided by vMAP
  crop_edge: 0